//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{

    public partial class comentario
    {
        public int cod { get; set; }
        public string usuario { get; set; }
        public string comentario1 { get; set; }
        public int cod_restaurante { get; set; }
    
        public virtual restaurante restaurante { get; set; }
    }
}
