//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyConnectionString : DbContext
    {
        public MyConnectionString()
            : base("name=MyConnectionString")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<restaurante> restaurante { get; set; }
        public DbSet<comentario> comentario { get; set; }
    }
}
