//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class restaurante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public restaurante()
        {
            this.comentario = new HashSet<comentario>();
        }
    
        public int cod { get; set; }
        public string nome { get; set; }
        public string tipo { get; set; }
        public string estilo { get; set; }
        public string horario { get; set; }
        public string endereço { get; set; }
        public string bairro { get; set; }
        public string cidade { get; set; }
        public string descricao { get; set; }
        public Nullable<int> avaliacao { get; set; }
        public byte[] imagem { get; set; }
    
        public virtual ICollection<comentario> comentario { get; set; }
    }
}
